var HEALTH_V5_RELATIONS = Object.freeze({
  'ClassroomDB.HomeroomStaffID': ['StaffDB', 'StaffID'],
  'StudentDB.ClassroomID': ['ClassroomDB', 'ClassroomID'],
  'StaffDB.RoleKey': ['RoleDB', 'RoleKey'],
  'PermissionDB.RoleKey': ['RoleDB', 'RoleKey'],
  'DutyDB.StaffID': ['StaffDB', 'StaffID'],
  'DrugDB.StudentID': ['StudentDB', 'StudentID'],
  'DrugDB.VerifiedByStaffID': ['StaffDB', 'StaffID'],
  'DrugDB.RecordedByStaffID': ['StaffDB', 'StaffID'],
  'NurseVisitItemDB.VisitID': ['NurseVisitDB', 'VisitID'],
  'NurseVisitItemDB.StockItemID': ['CommonDrugStockDB', 'StockItemID'],
  'NurseVisitItemDB.StockTransactionID': ['StockTransactionDB', 'StockTransactionID'],
  'NurseVisitItemDB.DispensedByStaffID': ['StaffDB', 'StaffID'],
  'NurseVisitDB.StudentID': ['StudentDB', 'StudentID'],
  'NurseVisitDB.RecordedByStaffID': ['StaffDB', 'StaffID'],
  'ReferDB.StudentID': ['StudentDB', 'StudentID'],
  'ReferDB.VisitID': ['NurseVisitDB', 'VisitID'],
  'ReferDB.ReferredByStaffID': ['StaffDB', 'StaffID'],
  'HealthDB.StudentID': ['StudentDB', 'StudentID'],
  'HealthDB.RecordedByStaffID': ['StaffDB', 'StaffID'],
  'FitnessDB.StudentID': ['StudentDB', 'StudentID'],
  'FitnessDB.TestedByStaffID': ['StaffDB', 'StaffID'],
  'LogDB.ActorID': ['StaffDB', 'StaffID'],
  'LogDB.RoleKey': ['RoleDB', 'RoleKey'],
  'StockTransactionDB.StockItemID': ['CommonDrugStockDB', 'StockItemID'],
  'StockTransactionDB.VisitItemID': ['NurseVisitItemDB', 'VisitItemID'],
  'StockTransactionDB.StudentID': ['StudentDB', 'StudentID'],
  'StockTransactionDB.RecordedByStaffID': ['StaffDB', 'StaffID'],
  'DiseaseEventDB.ParentEventID': ['DiseaseEventDB', 'DiseaseEventID'],
  'DiseaseEventDB.StudentID': ['StudentDB', 'StudentID'],
  'DiseaseEventDB.ResponsibleStaffID': ['StaffDB', 'StaffID'],
  'AssignmentDB.StaffID': ['StaffDB', 'StaffID'],
  'AssignmentDB.RoleKey': ['RoleDB', 'RoleKey'],
  'AssignmentDB.ApprovedByStaffID': ['StaffDB', 'StaffID'],
  'StudentDormHistoryDB.StudentID': ['StudentDB', 'StudentID'],
  'StudentDormHistoryDB.DormID': ['DormDB', 'DormID'],
  'StudentDormHistoryDB.RecordedByStaffID': ['StaffDB', 'StaffID'],
});

var HEALTH_V5_UNIQUE_FIELDS = Object.freeze({
  ConfigDB: [['ConfigID'], ['ConfigKey']],
  ClassroomDB: [['ClassroomID']],
  StudentDB: [['StudentID'], ['StudentCode']],
  StaffDB: [['StaffID'], ['Username']],
  RoleDB: [['RoleKey']],
  PermissionDB: [['PermissionID'], ['RoleKey', 'ResourceKey']],
  DutyDB: [['DutyID']],
  DrugDB: [['DrugPlanID']],
  NurseVisitItemDB: [['VisitItemID']],
  NurseVisitDB: [['VisitID']],
  ReferDB: [['ReferID']],
  HealthDB: [['HealthRecordID']],
  FitnessDB: [['FitnessRecordID']],
  LogDB: [['LogID']],
  CommonDrugStockDB: [['StockItemID'], ['ItemCode']],
  StockTransactionDB: [['StockTransactionID']],
  DiseaseEventDB: [['DiseaseEventID']],
  AssignmentDB: [['AssignmentID']],
  DormDB: [['DormID'], ['DormCode']],
  StudentDormHistoryDB: [['StudentDormHistoryID']],
});

var HEALTH_V5_AUDIT_ACTOR = 'SYSTEM_G2';
